import { TRANSPORT_MODES } from './transport';
import { findNearestAirport, getAirportsNearCity, AIRPORTS } from './airports';

const LONG_FLIGHT_THRESHOLD = 500;
const MEDIUM_FLIGHT_THRESHOLD = 200;

function haversineDistance(p1, p2) {
  const R = 6371;
  const dLat = (p2.lat - p1.lat) * Math.PI / 180;
  const dLng = (p2.lng - p1.lng) * Math.PI / 180;
  const a = Math.sin(dLat/2)**2 + Math.cos(p1.lat * Math.PI/180) * Math.cos(p2.lat * Math.PI/180) * Math.sin(dLng/2)**2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
}

function estimateFlightTime(distanceKm) {
  return (distanceKm / 800) * 3600 + 1800;
}

function estimateTrainTime(distanceKm) {
  return (distanceKm / 120) * 3600 + 600;
}

function estimateBusTime(distanceKm) {
  return (distanceKm / 60) * 3600 + 600;
}

export async function getSmartRoute(origin, destination) {
  const segments = [];
  const dist = haversineDistance(origin, destination);
  
  const originAirport = findNearestAirport(origin.lat, origin.lng, 150);
  const destAirport = findNearestAirport(destination.lat, destination.lng, 150);
  
  const needsFlight = dist > LONG_FLIGHT_THRESHOLD;
  const needsMediumTrip = dist > MEDIUM_FLIGHT_THRESHOLD;
  
  if (needsFlight && originAirport && destAirport && originAirport.code !== destAirport.code) {
    const distToOriginAirport = originAirport ? haversineDistance(origin, { lat: originAirport.lat, lng: originAirport.lng }) : 0;
    const distFromDestAirport = destAirport ? haversineDistance({ lat: destAirport.lat, lng: destAirport.lng }, destination) : 0;
    
    if (distToOriginAirport > 5) {
      segments.push({
        from: { ...origin, name: origin.name || 'Origen' },
        to: { lat: originAirport.lat, lng: originAirport.lng, name: `${originAirport.city} - ${originAirport.name}` },
        mode: distToOriginAirport > 30 ? 'bus' : 'driving',
        isAutoGenerated: true,
        description: `Ir a ${originAirport.name}`,
      });
    }
    
    const flightDistance = haversineDistance(
      { lat: originAirport.lat, lng: originAirport.lng },
      { lat: destAirport.lat, lng: destAirport.lng }
    );
    
    segments.push({
      from: { lat: originAirport.lat, lng: originAirport.lng, name: `${originAirport.city} - ${originAirport.name}` },
      to: { lat: destAirport.lat, lng: destAirport.lng, name: `${destAirport.city} - ${destAirport.name}` },
      mode: 'flight',
      isAutoGenerated: true,
      description: `Vuelo ${originAirport.code} → ${destAirport.code}`,
      estimatedDuration: estimateFlightTime(flightDistance),
    });
    
    if (distFromDestAirport > 5) {
      segments.push({
        from: { lat: destAirport.lat, lng: destAirport.lng, name: `${destAirport.city} - ${destAirport.name}` },
        to: { ...destination, name: destination.name || 'Destino' },
        mode: distFromDestAirport > 30 ? 'train' : 'walking',
        isAutoGenerated: true,
        description: `Desde ${destAirport.name} a destino`,
      });
    }
  } else if (needsMediumTrip) {
    segments.push({
      from: { ...origin, name: origin.name || 'Origen' },
      to: { ...destination, name: destination.name || 'Destino' },
      mode: dist > 300 ? 'train' : 'bus',
      isAutoGenerated: false,
    });
  } else {
    segments.push({
      from: { ...origin, name: origin.name || 'Origen' },
      to: { ...destination, name: destination.name || 'Destino' },
      mode: dist > 50 ? 'train' : dist > 10 ? 'bus' : 'walking',
      isAutoGenerated: false,
    });
  }
  
  let totalDistance = 0;
  let totalDuration = 0;
  
  for (const seg of segments) {
    if (seg.mode === 'flight') {
      seg.distance = haversineDistance(seg.from, seg.to) * 1000;
      seg.duration = seg.estimatedDuration || estimateFlightTime(seg.distance / 1000);
      seg.coordinates = [[seg.from.lng, seg.from.lat], [seg.to.lng, seg.to.lat]];
    } else if (seg.mode === 'walking' || seg.mode === 'bicycle') {
      seg.distance = haversineDistance(seg.from, seg.to) * 1000;
      const speed = seg.mode === 'walking' ? 5 : 15;
      seg.duration = (seg.distance / 1000 / speed) * 3600;
      seg.coordinates = [[seg.from.lng, seg.from.lat], [seg.to.lng, seg.to.lat]];
    } else {
      const distance = haversineDistance(seg.from, seg.to);
      if (seg.mode === 'train') {
        seg.distance = distance * 1000;
        seg.duration = estimateTrainTime(distance);
      } else {
        seg.distance = distance * 1000;
        seg.duration = estimateBusTime(distance);
      }
      seg.coordinates = [[seg.from.lng, seg.from.lat], [seg.to.lng, seg.to.lat]];
    }
    
    totalDistance += seg.distance;
    totalDuration += seg.duration;
  }
  
  return {
    segments,
    totalDistance,
    totalDuration,
    suggestion: generateSuggestion(segments, dist),
  };
}

function generateSuggestion(segments, directDistance) {
  const modes = segments.map(s => s.mode);
  const uniqueModes = [...new Set(modes)];
  
  const transportLabels = {
    flight: '✈️ vuelo',
    train: '🚄 tren',
    bus: '🚌 bus',
    driving: '🚗 coche',
    walking: '🚶 caminando',
    bicycle: '🚴 bicicleta',
  };
  
  const modeNames = uniqueModes.map(m => transportLabels[m] || m).join(' + ');
  
  return {
    summary: `Ruta sugerida: ${modeNames} (~${Math.round(directDistance)} km)`,
    segments: segments.map((seg, i) => ({
      index: i,
      from: seg.from.name,
      to: seg.to.name,
      mode: seg.mode,
      icon: TRANSPORT_MODES.find(m => m.id === seg.mode)?.icon || '📍',
    })),
  };
}

export function getSuggestedMode(distanceKm) {
  if (distanceKm < 5) return 'walking';
  if (distanceKm < 20) return 'bicycle';
  if (distanceKm < 100) return 'bus';
  if (distanceKm < 300) return 'train';
  if (distanceKm < 600) return 'flixbus';
  return 'flight';
}